import {test, expect} from './fixtures.mjs'

test('a short scan can be searched and cleared without selecting a node', async ({page}) => {
  await page.goto('/')
  const started = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/v1/scans')
  await page.getByRole('button', {name: /^(开始扫描|重新扫描)$/}).filter({visible: true}).click()
  const scan = await (await started).json()
  await expect(page.locator('.profile-scope select')).toHaveValue(scan.id)
  await expect(page.getByText('扫描完成', {exact: true})).toBeVisible()
  await expect(page.locator('.node-focus').first()).toBeVisible()
  const count = await page.locator('.node-focus').count()
  expect(count).toBeGreaterThan(1)
  expect(count).toBeLessThan(50)
  const mutations = []
  page.on('request', request => { if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method())) mutations.push(request.url()) })
  const search = page.getByRole('searchbox', {name: '搜索扫描结果', exact: true})
  await search.fill('JP-Osaka-02')
  await expect(page.locator('.node-focus')).toHaveCount(1)
  await page.getByRole('button', {name: '查看 JP-Osaka-02 详情', exact: true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('.table-search').getByRole('button', {name: '清空搜索'}).click()
  await expect(search).toBeFocused()
  await expect(search).toHaveValue('')
  await expect(page.locator('.node-focus')).toHaveCount(count)
  const belowRows = await page.locator('.ranking').evaluate(section => {
    const table = section.querySelector('table'), footer = section.querySelector('.list-pagination')
    return !!(table.compareDocumentPosition(footer) & Node.DOCUMENT_POSITION_FOLLOWING)
  })
  expect(belowRows).toBe(true)
  expect(mutations).toEqual([])
})

test('catalog sorting cycles through ascending, descending and original order in both languages', async ({page}) => {
  await page.goto('/#/nodes')
  await expect(page.locator('.catalog-node').first()).toBeVisible()
  await page.locator('.sort-select select').selectOption('original')
  const names = await page.locator('.catalog-node').allTextContents()
  const header = page.locator('.catalog th').first()
  await expect(header).toHaveAttribute('aria-sort', 'none')
  await header.getByRole('button', {name: '按节点名称升序排列'}).click()
  await expect(header).toHaveAttribute('aria-sort', 'ascending')
  await page.locator('.language-select select').selectOption('en')
  await expect(header).toHaveAttribute('aria-sort', 'ascending')
  await header.getByRole('button', {name: 'Sort Node name descending'}).click()
  await expect(header).toHaveAttribute('aria-sort', 'descending')
  await header.getByRole('button', {name: 'Restore original order (Node name)'}).click()
  await expect(header).toHaveAttribute('aria-sort', 'none')
  expect(await page.locator('.catalog-node').allTextContents()).toEqual(names)
  const search = page.getByRole('searchbox', {name: 'Search nodes', exact: true})
  await search.fill('JP-Osaka-02')
  await page.locator('.table-search').getByRole('button', {name: 'Clear search'}).click()
  await expect(search).toBeFocused()
  expect(await page.locator('.catalog-node').allTextContents()).toEqual(names)
})
