<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref,watch} from 'vue'
import {APIError,api,setAPIToken} from './api'
import type {Group,Health,NodeResult,Provider,Region,Scan,ScanPreview,SwitchEvent,NodeSummary} from './models'
type Page='scan'|'nodes'|'history'|'settings'
const page=ref<Page>('scan'),health=ref<Health|null>(null),groups=ref<Group[]>([]),providers=ref<Provider[]>([]),regions=ref<Region[]>([]),nodes=ref<NodeSummary[]>([]),history=ref<SwitchEvent[]>([])
const group=ref(''),areas=ref<string[]>([]),providerSet=ref<string[]>([]),mode=ref<'quick'|'stable'>('quick'),scan=ref<Scan|null>(null),preview=ref<ScanPreview|null>(null),running=ref(false),access=ref(false),token=ref(sessionStorage.getItem('mss-api-token')||''),theme=ref<'light'|'dark'>((localStorage.getItem('mss-theme')as 'light'|'dark')||'light'),notice=ref(''),failure=ref(''),query=ref(''),selected=ref<NodeSummary|null>(null)
let poll:number|undefined,stream:EventSource|undefined
const current=computed(()=>groups.value.find(x=>x.name===group.value));const results=computed(()=>scan.value?.results||[]);const best=computed(()=>results.value.find(x=>x.rank===1)||[...results.value].sort((a,b)=>b.score-a.score)[0]);const p=computed(()=>scan.value?.progress);const percent=computed(()=>p.value?.total?Math.round(p.value.completed*100/p.value.total):0)
const visibleNodes=computed(()=>nodes.value.filter(n=>(!query.value||n.name.toLowerCase().includes(query.value.toLowerCase()))&&(!areas.value.length||areas.value.includes(n.inferred_region||''))&&(!providerSet.value.length||providerSet.value.includes(n.provider||''))))
watch(theme,v=>{document.documentElement.dataset.theme=v;localStorage.setItem('mss-theme',v)},{immediate:true});watch([group,areas,providerSet,mode],()=>void preflight())
onMounted(()=>{setAPIToken(token.value);void load()});onBeforeUnmount(close)
async function load(){failure.value='';const r=await Promise.allSettled([api<Health>('/health'),api<Group[]>('/groups'),api<Provider[]>('/providers'),api<Region[]>('/regions'),api<NodeSummary[]>('/nodes'),api<SwitchEvent[]>('/history')]);if(r[0].status==='rejected'&&r[0].reason instanceof APIError&&r[0].reason.status===401){access.value=true;return}access.value=false;if(r[0].status==='fulfilled')health.value=r[0].value;if(r[1].status==='fulfilled'){groups.value=r[1].value;if(!group.value&&groups.value[0])group.value=groups.value[0].name}if(r[2].status==='fulfilled')providers.value=r[2].value;if(r[3].status==='fulfilled')regions.value=r[3].value;if(r[4].status==='fulfilled')nodes.value=r[4].value;if(r[5].status==='fulfilled')history.value=r[5].value||[];const bad=r.find(x=>x.status==='rejected') as PromiseRejectedResult|undefined;if(bad)failure.value=bad.reason instanceof Error?bad.reason.message:'无法加载 Mihomo 数据';await preflight()}
function unlock(){setAPIToken(token.value);sessionStorage.setItem('mss-api-token',token.value.trim());void load()}
function body(){return {target_group:group.value,regions:areas.value,providers:providerSet.value,mode:mode.value}}
function area(code:string){areas.value=areas.value.includes(code)?areas.value.filter(x=>x!==code):[...areas.value,code]}
function provider(name:string){providerSet.value=providerSet.value.includes(name)?providerSet.value.filter(x=>x!==name):[...providerSet.value,name]}
async function preflight(){if(!group.value||running.value)return;try{preview.value=await api<ScanPreview>('/scans/preflight',{method:'POST',body:JSON.stringify(body())})}catch{preview.value=null}}
async function start(){failure.value='';scan.value=await api<Scan>('/scans',{method:'POST',body:JSON.stringify(body())});running.value=true;stream=new EventSource('/api/v1/scans/'+encodeURIComponent(scan.value.id)+'/events');for(const n of ['batch-started','candidate-complete','completed','error'])stream.addEventListener(n,()=>void refresh());poll=window.setInterval(()=>void refresh(),1200)}
async function refresh(){if(!scan.value)return;scan.value=await api<Scan>('/scans/'+encodeURIComponent(scan.value.id));if(scan.value.status!=='running'){running.value=false;close();if(scan.value.status==='complete')notice.value=String(scan.value.results.length)+' 个节点已完成最终排名';else if(scan.value.status==='cancelled')notice.value='扫描已停止；保留 '+String(scan.value.results.length)+' 个暂定结果，不能用于切换';else failure.value=scan.value.error||'扫描失败'}}
async function stop(after:boolean){if(!scan.value)return;await api('/scans/'+encodeURIComponent(scan.value.id)+'/stop',{method:'POST',body:JSON.stringify({after_current_batch:after})});notice.value=after?'将在本批结束后停止':'正在停止扫描'}
async function choose(r?:NodeResult){const c=r||best.value;if(!scan.value||scan.value.status!=='complete'||!c)return;if(!confirm('将 '+(current.value?.now||'当前节点')+' 切换到 '+c.name+'？'))return;const e=await api<SwitchEvent>('/scans/'+encodeURIComponent(scan.value.id)+'/select',{method:'POST',body:JSON.stringify({node:c.name})});groups.value=groups.value.map(g=>g.name===e.group?{...g,now:e.selected}:g);history.value=[e,...history.value];notice.value='已切换到 '+e.selected}
function close(){if(poll!==undefined){clearInterval(poll);poll=undefined}stream?.close();stream=undefined}
function label(c?:string){const r=regions.value.find(x=>x.code===c);return r?(r.emoji||'')+' '+r.name:c||'Unknown'}function pc(v:number){return Math.round(v*100)+'%'}function ms(v?:number){return v?Math.round(v)+' ms':'—'}function clock(v?:number){return v?Math.floor(v/60)+':'+String(v%60).padStart(2,'0'):'—'}
</script>
<template>
<main v-if="access" class="access"><form @submit.prevent="unlock"><h1>Mihomo Smart Selector</h1><p>输入局域网访问 token。</p><label>LAN token<input v-model="token" type="password" autofocus></label><button :disabled="!token.trim()">安全连接</button></form></main>
<main v-else class="shell"><aside><div class="brand">Mihomo <small>Smart Selector</small></div><nav><button :class="{active:page==='scan'}" @click="page='scan'">扫描</button><button :class="{active:page==='nodes'}" @click="page='nodes'">节点</button><button :class="{active:page==='history'}" @click="page='history'">历史</button><button :class="{active:page==='settings'}" @click="page='settings'">设置</button></nav><footer>● {{health?.mihomo_connected?'Controller 已连接':'Controller 不可用'}}<small>手动选择 · 不自动切换</small></footer></aside>
<section class="work"><header><div><h1>{{page==='scan'?'扫描工作台':page==='nodes'?'节点目录':page==='history'?'选择历史':'偏好设置'}}</h1><p>{{page==='scan'?'先预检，再安全分批扫描。':'Mihomo Smart Selector'}}</p></div><button class="theme" @click="theme=theme==='light'?'dark':'light'">{{theme==='light'?'深色':'明亮'}}主题</button></header><div v-if="failure" class="notice error">{{failure}}</div><div v-if="notice" class="notice">{{notice}}</div>
<section v-if="page==='scan'"><div class="command"><label>目标<select v-model="group"><option v-for="g in groups" :key="g.name" :value="g.name">{{g.name}}</option></select></label><div class="chips"><b>地区</b><button :class="{active:!areas.length}" @click="areas=[]">All</button><button v-for="r in regions" :key="r.code" :class="{active:areas.includes(r.code)}" @click="area(r.code)">{{r.emoji}} {{r.name}}</button></div><details><summary>Provider · {{providerSet.length||'全部'}}</summary><label v-for="x in providers" :key="x.name"><input type="checkbox" :checked="providerSet.includes(x.name)" @change="provider(x.name)">{{x.name}}</label></details><label>模式<select v-model="mode"><option value="quick">Quick</option><option value="stable">Stable</option></select></label><button class="primary" :disabled="running||!group" @click="start">{{running?'扫描中':'开始扫描'}}</button></div>
<div v-if="!running" class="preflight"><b>{{preview?.candidate_count||0}} 个候选 · {{preview?.batch_count||0}} 批</b><span>{{preview?.probe_requests||0}} 次探测；开始后不会改变节点。</span></div>
<div v-if="running" class="progress"><div><b>已完成 {{p?.completed||0}} / {{p?.total||0}} · 第 {{p?.current_batch||0}} / {{p?.total_batches||0}} 批</b><strong>{{percent}}%</strong></div><i><span :style="{width:percent+'%'}"></span></i><section><span>成功 <b>{{p?.succeeded||0}}</b></span><span>失败 <b>{{p?.failed||0}}</b></span><span>耗时 <b>{{clock(p?.elapsed_seconds)}}</b></span><span>预计剩余 <b>{{clock(p?.estimated_remaining_seconds)}}</b></span></section><p><button @click="stop(true)">本批结束后停止</button><button class="danger" @click="stop(false)">立即停止</button></p></div>
<div class="grid"><section class="panel"><div class="head"><div><h2>{{scan?.status==='complete'?'最终排名':'暂定结果'}}</h2><p>{{scan?.status==='complete'?'只有确认后才会切换。':'最终排名尚未生成，所有选择操作保持锁定。'}}</p></div><button v-if="best&&scan?.status==='complete'" class="primary" @click="choose()">选择最佳节点</button></div><div class="scroll"><table><thead><tr><th>#</th><th>节点</th><th>地区</th><th>成功</th><th>P95</th><th>Score</th><th></th></tr></thead><tbody><tr v-for="r in results" :key="r.name"><td>{{r.rank||'—'}}</td><td><b>{{r.name}}</b><small>{{r.provider}}</small></td><td>{{label(r.inferred_region)}}</td><td>{{pc(r.success_rate)}}</td><td>{{ms(r.p95_ms)}}</td><td class="score">{{r.score.toFixed(1)}}</td><td><button :disabled="scan?.status!=='complete'||r.success_rate<.95" @click="choose(r)">选择</button></td></tr><tr v-if="!results.length"><td colspan="7">开始扫描后，部分结果会实时出现。</td></tr></tbody></table></div></section><aside class="panel compare"><h2>当前与候选</h2><div class="vs"><div><small>当前节点</small><b>{{current?.now||'—'}}</b></div><em>VS</em><div><small>最佳候选</small><b>{{best?.name||'等待结果'}}</b></div></div><dl><div><dt>成功率</dt><dd>{{best?pc(best.success_rate):'—'}}</dd></div><div><dt>P95</dt><dd>{{best?ms(best.p95_ms):'—'}}</dd></div><div><dt>Score</dt><dd>{{best?best.score.toFixed(1):'—'}}</dd></div></dl><p>{{scan?.status==='complete'?'比较后确认切换。':'扫描未完成或已停止，选择操作保持锁定。'}}</p></aside></div></section>
<section v-else-if="page==='nodes'"><div class="toolbar"><input v-model="query" placeholder="搜索节点"><b>{{visibleNodes.length}} / {{nodes.length}} 个叶子节点</b></div><div class="nodegrid"><section class="panel scroll"><table><thead><tr><th>节点</th><th>地区</th><th>Provider</th><th>协议</th></tr></thead><tbody><tr v-for="n in visibleNodes" :key="n.name" @click="selected=n"><td>{{n.name}}</td><td>{{label(n.inferred_region)}}</td><td>{{n.provider||'—'}}</td><td>{{n.protocol||'—'}}</td></tr></tbody></table></section><aside class="panel"><h2>节点详情</h2><template v-if="selected"><b>{{selected.name}}</b><p>{{label(selected.inferred_region)}} · {{selected.region_source}}</p><p>Provider：{{selected.provider||'—'}}</p><p>协议：{{selected.protocol||'—'}}</p></template><p v-else>选择节点查看地区推断。</p></aside></div></section>
<section v-else-if="page==='history'" class="panel"><h2>手动切换记录</h2><article v-for="h in history" :key="h.id"><small>{{new Date(h.created_at).toLocaleString()}}</small><b>{{h.previous||'—'}} → {{h.selected}}</b><span>{{h.group}}</span></article><p v-if="!history.length">尚无手动切换记录。</p></section>
<section v-else class="settings"><div class="panel"><h2>外观</h2><p>主题偏好保存在当前浏览器。</p><button class="primary" @click="theme=theme==='light'?'dark':'light'">切换主题</button></div><div class="panel"><h2>扫描安全</h2><p>预检显示候选和批次；扫描期间可以立即停止，或在本批结束后安全停止。</p></div></section>
</section></main></template>
